classdef SLIMfast < handle
    %written by
    %C.P.Richter
    %Division of Biophysics / Group J.Piehler
    %University of Osnabrueck
    
    properties
        Build = '16f'
    end %properties
    properties(Hidden, Transient)
        hFig
        hMenuBar
        hChangelogFig
        
        objProjectExplorer
        objProjectConstructor
        objDataImport
        objBatchProcessor
        objRecentFileManager
        
        Profile
        
        Projects
    end %properties
    
    events
        ObjectDestruction
    end %events
    
    methods
        %constructor
        function this = SLIMfast
            % check for proper Matlab Version
            if verLessThan('matlab', '7.12.0.635')
                waitfor(errordlg(...
                    'Matlab 2011a or higher required to run SLIMfast.',...
                    'Critical Error','modal'))
                return
            end %if
            
            % check for essential Matlab Toolboxes
            essentialToolboxes = {...
                'Image_Toolbox','Optimization_Toolbox','Statistics_Toolbox'};
            hasToolbox = false(1,numel(essentialToolboxes));
            for idxToolbox = 1:numel(essentialToolboxes)
                hasToolbox(idxToolbox) = ...
                    license('checkout',essentialToolboxes{idxToolbox});
            end %for
            if any(~hasToolbox)
                waitfor(errordlg(...
                    char('Essential Matlab Toolbox(es) missing:',...
                    char(strrep(essentialToolboxes(~hasToolbox),'_',' '))),...
                    'Critical Error','modal'))
                return
            end %if
            
            % check if there is an instance of SLIMfast already running
            if isappdata(0,'objSLIMfast')
                waitfor(errordlg(...
                    'Only one running instance of SLIMfast allowed.',...
                    'Critical Error','modal'))
                return
            else
                setappdata(0,'objSLIMfast', this)
                
                %get actual SLIMfast directory
                SLIMfastPath = pwd;
                setappdata(0,'SLIMfastPath', SLIMfastPath)
                setappdata(0,'searchPath', SLIMfastPath)
                
                %add SLIMfast-folder and subfolders to matlab
                addpath(genpath(SLIMfastPath))
                
                %load icons from disc
                loaded = load([SLIMfastPath filesep 'icon.mat']);
                setappdata(0,'icon', loaded.icon)
            end %if
            
            % turn off known warnings
            warning('off','Images:imageDisplayValidateParams:colormapWithTruecolor')
            warning('off','MATLAB:hg:JavaSetHGProperty')
            warning('off','MATLAB:hg:PossibleDeprecatedJavaSetHGProperty')
            warning('off','MATLAB:TriScatteredInterp:DupPtsAvValuesWarnId')
            warning('off','MATLAB:imagesci:tiffmexutils:libtiffErrorAsWarning') %CPR 22.04.2015
            
            %set default axes behaviour
            iptsetpref('ImshowAxesVisible','off')
            set(0,'DefaultFigureColor',[1 1 1])
            set(0,'DefaultAxesFontName', 'Calibri')
            set(0,'DefaultAxesFontSize',24)
            set(0,'DefaultTextFontName', 'Calibri')
            set(0,'DefaultTextFontSize',24)
            
            % set tooltips to appear immediately
            tm = javax.swing.ToolTipManager.sharedInstance;
            javaMethodEDT('setInitialDelay',tm,0);
            javaMethodEDT('setDismissDelay',tm,10000);
            
            % setup SLIMfast GUI
            scrSize = get(0, 'ScreenSize');
            this.hFig =...
                figure(...
                'Units','pixels',...
                'Position', [0.5*(scrSize(3)-800) 0.5*(scrSize(4)-500) 800 500],...
                'Name', ['SLIMfast NextGen ' this.Build],...
                'NumberTitle', 'off',...
                'MenuBar', 'none',...
                'ToolBar', 'none',...
                'DockControls', 'off',...
                'Resize', 'on',...
                'IntegerHandle','off',...
                'Color', get(0, 'DefaultUIControlBackgroundColor'),...
                'CloseRequestFcn', @(src,evnt)close_SLIMfast(this),...
                'Visible','off');
            
            generate_menubar(this)
            load_user_profiles(this)
            
            this.objProjectExplorer = ProjectExplorer(this);
            this.objProjectConstructor = ProjectConstructor(this);
            this.objDataImport = ManagerFileImport(this);
            this.objBatchProcessor = ClassBatch(this);
            this.objRecentFileManager = ManagerRecentFiles(this);
            
            set(this.hFig,...
                'Units','normalized',...
                'Visible','on')
        end %fun
        %destructor
        function close_SLIMfast(this)
            answer = questdlg('Close SLIMfast?', ...
                '', 'Yes', 'No', 'Yes');
            switch answer
                case 'Yes'
                    %send signal to close
                    notify(this,'ObjectDestruction')
                    
                    %close main figure
                    delete(this.hFig)
                    delete(this)
                    
                    rmpath(genpath(getappdata(0,'SLIMfastPath')))
                    
                    rmappdata(0,'objSLIMfast')
                    rmappdata(0,'SLIMfastPath')
                    rmappdata(0,'searchPath')
                    rmappdata(0,'icon')
                case 'No'
                    %do nothing
            end %switch
        end %fun
        
        %%
        function generate_menubar(this)
            hMenuProject =...
                uimenu(...
                'Label', 'Project');
            
            hMenuCreateProject =...
                uimenu(...
                'Parent', hMenuProject,...
                'Label', 'Create',...
                'Callback', @(src,evnt)open_project_constructor(this.objProjectConstructor));
            
            hMenuLoadProject =...
                uimenu(...
                'Parent', hMenuProject,...
                'Label', 'Load');
            uimenu(...
                'Parent', hMenuLoadProject,...
                'Label', 'Select Project File',...
                'Separator','on',...
                'Callback', @(src,evnt)select_saved_project(this));
            
            hMenuImportProject = ...
                uimenu(...
                'Parent', hMenuProject,...
                'Label', 'Import',...
                'Callback', @(src,evnt)import_SLIMfast_old_generation(this.objDataImport));
            
            hMenuCombineProject =...
                uimenu(...
                'Parent', hMenuProject,...
                'Label', 'Combine',...
                'Separator','on',...
                'Callback', @(src,evnt)combine_project(this,src),...
                'Enable', 'off');
            hMenuCombineAllProject =...
                uimenu(...
                'Parent', hMenuProject,...
                'Label', 'Combine All',...
                'Callback', @(src,evnt)combine_project(this,src),...
                'Enable', 'off');
            
            hMenuSaveProject =...
                uimenu(...
                'Parent', hMenuProject,...
                'Separator','on',...
                'Label', 'Save',...
                'Callback', @(src,evnt)save_project(this,src),...
                'Enable', 'off');
            hMenuSaveAllProject =...
                uimenu(...
                'Parent', hMenuProject,...
                'Label', 'Save All',...
                'Callback', @(src,evnt)save_project(this,src),...
                'Enable', 'off');
            hMenuSaveAsProject =...
                uimenu(...
                'Parent', hMenuProject,...
                'Label', 'Save As',...
                'Callback', @(src,evnt)save_project(this,src),...
                'Enable', 'off');
            hMenuSaveAsAllProject =...
                uimenu(...
                'Parent', hMenuProject,...
                'Label', 'Save All As',...
                'Callback', @(src,evnt)save_project(this,src),...
                'Enable', 'off');
            
            hMenuCloseProject =...
                uimenu(...
                'Parent', hMenuProject,...
                'Separator','on',...
                'Label', 'Close',...
                'Callback', @(src,evnt)log_out_project(this,src),...
                'Enable', 'off');
            hMenuCloseAllProject =...
                uimenu(...
                'Parent', hMenuProject,...
                'Label', 'Close All',...
                'Callback', @(src,evnt)log_out_project(this,src),...
                'Enable', 'off');
            
            hMenuData =...
                uimenu(...
                'Label', 'Data');
            hMenuDataExpandAll =...
                uimenu(...
                'Parent', hMenuData,...
                'Label', 'Expand All',...
                'Callback',@(src,evnt)expand_all(this.objProjectExplorer));
            
            
            hMenuDataCollapseAll =...
                uimenu(...
                'Parent', hMenuData,...
                'Label', 'Collapse All',...
                'Callback',@(src,evnt)collapse_all(this.objProjectExplorer));
            
            hMenuDataRaw =...
                uimenu(...
                'Parent', hMenuData,...
                'Separator','on',...
                'Label', 'Raw');
            hMenuDataRawSelectAll =...
                uimenu(...
                'Parent', hMenuDataRaw,...
                'Label', 'Select All',...
                'Callback',@(src,evnt)select_leafs(this.objProjectExplorer,'ClassRaw'));
            uimenu(...
                'Parent', hMenuDataRaw,...
                'Label', 'Unit Conversion Factors',...
                'Separator', 'on',...
                'Callback',@(src,evnt)set_conversion_factors(this.objBatchProcessor));
            uimenu(...
                'Parent', hMenuDataRaw,...
                'Label', 'Localization',...
                'Callback',@(src,evnt)particle_localization(this.objBatchProcessor));
            
            hMenuDataLoc =...
                uimenu(...
                'Parent', hMenuData,...
                'Label', 'Localization');
            hMenuDataLocSelectAll =...
                uimenu(...
                'Parent', hMenuDataLoc,...
                'Label', 'Select All',...
                'Callback',@(src,evnt)select_leafs(this.objProjectExplorer,'ClassLocalization'));
            uimenu(...
                'Parent', hMenuDataLoc,...
                'Label', 'Immobile Filter',...
                'Separator', 'on',...
                'Callback',@(src,evnt)filter_immobile(this.objBatchProcessor));
            uimenu(...
                'Parent', hMenuDataLoc,...
                'Label', 'Co-Localization',...
                'Callback',@(src,evnt)dualview_colocalization(this.objBatchProcessor));
            uimenu(...
                'Parent', hMenuDataLoc,...
                'Label', 'Tracking',...
                'Callback',@(src,evnt)particle_tracking(this.objBatchProcessor));
            hMenuDataCluster =...
                uimenu(...
                'Parent', hMenuData,...
                'Label', 'Cluster');
            hMenuDataClusterSelectAll =...
                uimenu(...
                'Parent', hMenuDataCluster,...
                'Label', 'Select All',...
                'Callback',@(src,evnt)select_leafs(this.objProjectExplorer,'ClassCluster'));
            hMenuDataClusterPool =...
                uimenu(...
                'Parent', hMenuDataCluster,...
                'Label', 'Pool',...
                'Separator', 'on',...
                'Callback',@(src,evnt)pool_clusters(this.objBatchProcessor));
            
            hMenuDataTraj =...
                uimenu(...
                'Parent', hMenuData,...
                'Label', 'Trajectory');
            hMenuDataTrajSelectAll =...
                uimenu(...
                'Parent', hMenuDataTraj,...
                'Label', 'Select All',...
                'Callback',@(src,evnt)select_leafs(this.objProjectExplorer,'ClassTrajectory'));
            hMenuDataTrajPool =...
                uimenu(...
                'Parent', hMenuDataTraj,...
                'Label', 'Pool',...
                'Separator', 'on',...
                'Callback',@(src,evnt)pool_trajectories(this.objBatchProcessor));
            %             hMenuDataTrajJumpseries =...
            %                 uimenu(...
            %                 'Parent', hMenuDataTraj,...
            %                 'Label', 'Jumpseries Analysis',...
            %                 'Callback',@(src,evnt)jumpseries_analysis(this.objBatchProcessor));
            
            hMenuDataComposite =...
                uimenu(...
                'Parent', hMenuData,...
                'Label', 'Composite');
            hMenuDataCompositeSelectAll =...
                uimenu(...
                'Parent', hMenuDataComposite,...
                'Label', 'Select All',...
                'Callback',@(src,evnt)select_leafs(this.objProjectExplorer,'ClassComposite'));
            hMenuDataCompositeCreate =...
                uimenu(...
                'Parent', hMenuDataComposite,...
                'Label', 'Create',...
                'Separator', 'on',...
                'Callback',@(src,evnt)create_empty_composite_container(this.objProjectExplorer));
            
            %             hMenuDataBatchProcess =...
            %                 uimenu(...
            %                 'Parent', hMenuData,...
            %                 'Label', 'Batch Process',...
            %                 'Separator','on',...
            %                 'Enable','off');
            
            hMenuExtra =...
                uimenu(...
                'Label', 'Extras');
            hMenuExtraProfile = ...
                uimenu(...
                'Parent', hMenuExtra,...
                'Label', 'Profile');
            
            hMenuExtraHelp = ...
                uimenu(...
                'Parent', hMenuExtra,...
                'Label', 'Help',...
                'Callback', @show_help,...
                'Enable', 'off',...
                'Separator', 'on');
            hMenuExtraChangelog = ...
                uimenu(...
                'Parent', hMenuExtra,...
                'Label', 'Changelog',...
                'Callback', @(src,evnt)show_changelog(this));
            hMenuExtraCredits = ...
                uimenu(...
                'Parent', hMenuExtra,...
                'Label', 'Credits',...
                'Callback', @show_credits,...
                'Enable', 'off',...
                'Separator', 'on');
            
            this.hMenuBar = struct(...
                'Project', struct(...
                'MenuProject', hMenuProject,...
                'Create', hMenuCreateProject,...
                'Load', hMenuLoadProject,...
                'Import', hMenuImportProject,...
                'Combine', hMenuCombineProject,...
                'CombineAll', hMenuCombineAllProject,...
                'Save', hMenuSaveProject,...
                'SaveAll', hMenuSaveAllProject,...
                'SaveAs', hMenuSaveAsProject,...
                'SaveAsAll', hMenuSaveAsAllProject,...
                'Close', hMenuCloseProject,...
                'CloseAll', hMenuCloseAllProject),...
                'Data', struct(...
                'MenuData', hMenuData,...
                'ExpandAll', hMenuDataExpandAll,...
                'CollapseAll', hMenuDataCollapseAll,...
                'Raw', struct(...
                'MenuRaw', hMenuDataRaw,...
                'SelectAll', hMenuDataRawSelectAll),...
                'Loc', struct(...
                'MenuLoc', hMenuDataLoc,...
                'SelectAll', hMenuDataLocSelectAll),...
                'Traj', struct(...
                'MenuTraj', hMenuDataTraj,...
                'SelectAll', hMenuDataTrajSelectAll,...
                'Pool', hMenuDataTrajPool),...
                'Cluster', struct(...
                'MenuCluster', hMenuDataCluster,...
                'SelectAll', hMenuDataClusterSelectAll,...
                'Pool', hMenuDataClusterPool),...
                'Composite', struct(...
                'MenuComposite', hMenuDataComposite,...
                'SelectAll', hMenuDataCompositeSelectAll,...
                'Create', hMenuDataCompositeCreate)),...
                'Extra', struct(...
                'Profile', hMenuExtraProfile,...
                'Changelog', hMenuExtraChangelog,...
                'Help', hMenuExtraHelp,...
                'Credits', hMenuExtraCredits));
        end %fun
        
        %%
        function combine_project(this,src)
            %initialize combined project
            objTargetProject = ClassProject;
            set_parent(objTargetProject,this)
            
            switch get(src,'Label')
                case 'Combine'
                    [hSelectedList,numSelected] = ...
                        get_user_selected_nodes(this.objProjectExplorer);
                    
                    %check that > 1 project is selected
                    if numSelected < 2
                        waitfor(errordlg('Less than 2 projects selected','','modal'))
                        return
                    end %if
                    
                    for idxSelection = 1:numSelected
                        objProject = get(hSelectedList(idxSelection),'UserData');
                        
                        for classIdx = 1:5
                            if ~isempty(objProject.objData{classIdx})
                                arrayfun(@(x)set_parent(x,objTargetProject),...
                                    objProject.objData{classIdx},'Un',0)
                                objTargetProject.objData{classIdx} = ...
                                    [objTargetProject.objData{classIdx};...
                                    objProject.objData{classIdx}];
                            end %if
                        end %for
                        objProject.hProjectNode.removeAllChildren
                        log_out_project(this,objProject)
                    end %for
                case 'Combine All'
                    %check that there is more than one project
                    if numel(this.Projects) == 1
                        waitfor(errordlg('Less than 2 projects exist','','modal'))
                        return
                    end %if
                    
                    while ~isempty(this.Projects)
                        objProject = this.Projects(1);
                        
                        for classIdx = 1:5
                            if ~isempty(objProject.objData{classIdx})
                                arrayfun(@(x)set_parent(x,objTargetProject),...
                                    objProject.objData{classIdx},'Un',0)
                                objTargetProject.objData{classIdx} = ...
                                    [objTargetProject.objData{classIdx};...
                                    objProject.objData{classIdx}];
                            end %if
                        end %for
                        objProject.hProjectNode.removeAllChildren
                        log_out_project(this,objProject)
                    end %for
            end %switch
            log_in_project(this,objTargetProject)
        end %fun
        function save_project(this,src)
            switch get(src,'Label')
                case 'Save'
                    selection = this.objProjectExplorer.hProjectTree.getTree.getLastSelectedPathComponent;
                    if strcmp(get(selection,'Value'),'IsProjectNode')
                        objProject = get(selection,'UserData');
                        if exist(objProject.SaveTo,'file') == 2
                            
                            hProgressbar = ClassProgressbar({'Saving Project...'});
                            start_loop(hProgressbar,0.05)
                            %                             savefast(objProject.SaveTo,'objProject')
                            save(objProject.SaveTo,'objProject','-mat','-v6')
                            %                             save(objProject.SaveTo,'objProject','-mat','-v7')
                            stopp_loop(hProgressbar)
                            close_progressbar(hProgressbar)
                            
                            waitfor(msgbox(sprintf(...
                                '%s saved to:\n%s',objProject.Name,objProject.SaveTo),'modal'))
                        else
                            [filename,pathname,isOK] =...
                                uiputfile(...
                                {'*.project', 'SLIMfast Project (.project)'},...
                                'Save to', [getappdata(0,'searchPath') filesep ...
                                objProject.Name '.project']);
                            if isOK
                                setappdata(0,'searchPath',pathname)
                                
                                hProgressbar = ClassProgressbar({'Saving Project...'});
                                start_loop(hProgressbar,0.05)
                                %                                 savefast([pathname filename],'objProject')
                                save([pathname filename],'objProject','-mat','-v6')
                                %                                 save([pathname filename],'objProject','-mat','-v7')
                                objProject.SaveTo = [pathname filename];
                                stopp_loop(hProgressbar)
                                close_progressbar(hProgressbar)
                                
                                waitfor(msgbox(sprintf(...
                                    '%s saved to:\n%s',objProject.Name,objProject.SaveTo),'modal'))
                            else
                                waitfor(errordlg('No Target Folder selected','','modal'))
                            end %if
                        end %if
                    else
                        waitfor(errordlg('No Project selected','','modal'))
                    end %if
                case 'Save All'
                    hProgressbar = ClassProgressbar({'Saving Project(s)...'});
                    start_loop(hProgressbar,0.05)
                    
                    numProj = numel(this.Projects);
                    for idx = 1:numProj
                        objProject = this.Projects(idx);
                        if exist(objProject.SaveTo,'file') == 2
                            %                             savefast(objProject.SaveTo,'objProject')
                            %                             save(objProject.SaveTo,'objProject','-mat','-v7')
                            save(objProject.SaveTo,'objProject','-mat','-v6')
                        else
                            [filename,pathname,isOK] =...
                                uiputfile(...
                                {'*.project', 'SLIMfast Project (.project)'},...
                                'Save to', [getappdata(0,'searchPath') filesep ...
                                objProject.Name '.project']);
                            if isOK
                                setappdata(0,'searchPath',pathname)
                                
                                %                                 savefast([pathname filename],'objProject')
                                save([pathname filename],'objProject','-mat','-v6')
                                %                                 save([pathname filename],'objProject','-mat','-v7')
                                objProject.SaveTo = [pathname filename];
                            end %if
                        end %if
                    end %for
                    stopp_loop(hProgressbar)
                    close_progressbar(hProgressbar)
                    
                    waitfor(msgbox(strcat(...
                        'My Projects\',...
                        char(arrayfun(@(x)x.Name,this.Projects,'Un',0).'),' ->',...
                        char(arrayfun(@(x)x.SaveTo,this.Projects,'Un',0).')),...
                        'All Projects saved','modal'))
                case 'Save As'
                    selection = this.objProjectExplorer.hProjectTree.getTree.getLastSelectedPathComponent;
                    %check if selection is project node
                    if strcmp(get(selection,'Value'),'IsProjectNode')
                        objProject = get(selection,'UserData');
                        
                        [filename,pathname,isOK] =...
                            uiputfile(...
                            {'*.project', 'SLIMfast Project (.project)'},...
                            'Save to', [getappdata(0,'searchPath') filesep ...
                            objProject.Name '.project']);
                        if isOK
                            setappdata(0,'searchPath',pathname)
                            
                            hProgressbar = ClassProgressbar({'Saving Project...'});
                            start_loop(hProgressbar,0.05)
                            %                             savefast([pathname filename],'objProject')
                            %                             save([pathname filename],'objProject','-mat','-v7')
                            save([pathname filename],'objProject','-mat','-v6')
                            objProject.SaveTo = [pathname filename];
                            stopp_loop(hProgressbar)
                            close_progressbar(hProgressbar)
                            
                            waitfor(msgbox(sprintf(...
                                '%s saved to:\n%s',objProject.Name,objProject.SaveTo),'modal'))
                        end %if
                    else
                        waitfor(errordlg('No Project selected','','modal'))
                    end %if
                case 'Save All As'
                    [filename,pathname,isOK] =...
                        uiputfile(...
                        {'*.project', 'SLIMfast Project (.project)'},...
                        'Save to', getappdata(0,'searchPath'));
                    if isOK
                        hProgressbar = ClassProgressbar({'Saving Project(s)...'});
                        start_loop(hProgressbar,0.05)
                        
                        numProj = numel(this.Projects);
                        for idx = 1:numProj
                            objProject = this.Projects(idx);
                            
                            %                             savefast([pathname filename(1:end-8) '_' num2str(idx)...
                            %                                 filename(end-7:end)],'objProject')
                            save([pathname filename(1:end-8) '_' num2str(idx)...
                                filename(end-7:end)],'objProject','-mat','-v6')
                            %                             save([pathname filename(1:end-8) '_' num2str(idx)...
                            %                                 filename(end-7:end)],'objProject','-mat','-v7')
                            objProject.SaveTo = ...
                                [pathname filename(1:end-8) '_' num2str(idx)...
                                filename(end-7:end)];
                        end %for
                        
                        waitfor(msgbox(strcat(...
                            'My Projects\',...
                            char(arrayfun(@(x)x.Name,this.Projects,'Un',0).'),' ->',...
                            char(arrayfun(@(x)x.SaveTo,this.Projects,'Un',0).')),...
                            'All Projects saved','modal'))
                    end %if
            end %switch
        end %fun
        function select_saved_project(this)
            [filename, pathname, isOK] = uigetfile(...
                {'*.project', 'SLIMfast Project (.project)'},...
                'Select Project',getappdata(0,'searchPath'),...
                'MultiSelect','on');
            if isOK
                setappdata(0,'searchPath',pathname)
                if iscell(filename)
                    numFiles = numel(filename);
                    for idxFile = 1:numFiles
                        open_project(this,[pathname filename{idxFile}])
                    end %for
                else
                    open_project(this,[pathname filename])
                end %if
            else
                waitfor(errordlg('No File selected','','modal'))
            end %if
        end %fun
        function open_project(this,filename)
            if exist(filename,'file')
                hProgressbar = ClassProgressbar({'Loading Project...'});
                start_loop(hProgressbar,0.05)
                
                loaded = load(filename,'objProject','-mat');
                set_parent(loaded.objProject,this)
                loaded.objProject.SaveTo = filename;
                
                log_in_project(this,loaded.objProject)
                update_menu_entries(this.objRecentFileManager,...
                    filename)
                
                stopp_loop(hProgressbar)
                close_progressbar(hProgressbar)
            else
                waitfor(errordlg(sprintf('File not found:\n%s',filename),'modal'))
            end %if
        end %fun
        
        %%
        function log_in_project(this,objProject)
            %add project reference to list
            this.Projects = [this.Projects; objProject];
            load_node_structure(this.objProjectExplorer,objProject);
            
            set([this.hMenuBar.Project.Save ...
                this.hMenuBar.Project.SaveAs ...
                this.hMenuBar.Project.Close],'Enable','on')
            if numel(this.Projects) > 1
                set([this.hMenuBar.Project.SaveAll ...
                    this.hMenuBar.Project.SaveAsAll ...
                    this.hMenuBar.Project.Combine ...
                    this.hMenuBar.Project.CombineAll ...
                    this.hMenuBar.Project.CloseAll],'Enable','on')
            end %if
        end %fun
        function log_out_project(this,src)
            if ishghandle(src)
                switch get(src,'Label')
                    case 'Close'
                        selection = ...
                            this.objProjectExplorer.jProjectTree.getLastSelectedPathComponent;
                        %check if selection is project node
                        if strcmp(get(selection,'Value'),'IsProjectNode')
                            objProject = get(selection,'UserData');
                            
                            %remove reference to deleted project
                            idx = eq(this.Projects,objProject);
                            %send close order
                            delete_object(objProject)
                            %remove project from list
                            this.Projects(idx) = [];
                        end %if
                    case 'Close All'
                        %send close order until all project are closed
                        hProgressbar = ClassProgressbar({'Closing Project(s)...'});
                        
                        numProj = numel(this.Projects);
                        for idx = 1:numProj
                            %send close order
                            delete_object(this.Projects(idx))
                            
                            update_progressbar(hProgressbar,{idx/numProj})
                        end %for
                        close_progressbar(hProgressbar)
                        
                        this.Projects = [];
                end %switch
            elseif isobject(src)
                if isa(src,'ClassProject') %(src=objProject)
                    objProject = src;
                    %remove reference to deleted project
                    idxProject = eq(this.Projects,objProject);
                    %remove project from list
                    this.Projects(idxProject) = [];
                    
                    %send delete order
                    delete_object(objProject)
                end %if
            end %if
            
            if numel(this.Projects) < 1
                set([...
                    this.hMenuBar.Project.Save ...
                    this.hMenuBar.Project.SaveAll ...
                    this.hMenuBar.Project.SaveAs ...
                    this.hMenuBar.Project.SaveAsAll ...
                    this.hMenuBar.Project.Combine ...
                    this.hMenuBar.Project.CombineAll ...
                    this.hMenuBar.Project.Close ...
                    this.hMenuBar.Project.CloseAll],'Enable','off')
            elseif numel(this.Projects) == 1
                set([...
                    this.hMenuBar.Project.SaveAll ...
                    this.hMenuBar.Project.SaveAsAll ...
                    this.hMenuBar.Project.Combine ...
                    this.hMenuBar.Project.CombineAll ...
                    this.hMenuBar.Project.CloseAll],'Enable','off')
            end %if
            
            this.objProjectExplorer.hProjectTree.setSelectedNode(...
                this.objProjectExplorer.hRootNode)
            update_project_tree(this.objProjectExplorer)
        end %fun
        
        %%
        function load_user_profiles(this)
            %standard profile
            this.Profile = ...
                uimenu(...
                'Parent', this.hMenuBar.Extra.Profile,...
                'Label', 'Standard',...
                'Checked', 'on',...
                'Callback', @(src,evnt)set_contextmenu_state(src,1));
            
            %user profiles
            SLIMfastPath = getappdata(0,'SLIMfastPath');
            files = dir([SLIMfastPath filesep 'Profiles' filesep '*.txt']);
            for idxFile = 1:numel(files)
                this.Profile(idxFile+1) = ...
                    uimenu(...
                    'Parent', this.hMenuBar.Extra.Profile,...
                    'Label', files(idxFile).name(1:end-4),...
                    'Callback', @(src,evnt)set_contextmenu_state(src,1));
            end %for
        end %fun
        function show_changelog(this)
            if ishandle(this.hChangelogFig)
                waitfor(errordlg('Changelog is already open','','modal'))
                figure(this.hChangelogFig)
            else
                this.hChangelogFig =...
                    figure(...
                    'Units','pixels',...
                    'Position', set_figure_position(1.5, 0.6, 'center'),...
                    'Color', get(0,'defaultUicontrolBackgroundColor'),...
                    'Name', sprintf('Changelog for Build %s',this.Build),...
                    'NumberTitle', 'off',...
                    'MenuBar', 'none',...
                    'ToolBar', 'none',...
                    'Resize', 'off');
                hList =...
                    uicontrol(...
                    'Style', 'listbox',...
                    'Parent', this.hChangelogFig,...
                    'Units','normalized',...
                    'Position', [0 0 1 1],...
                    'FontSize', 10,...
                    'FontUnits', 'normalized',...
                    'FontWeight', 'bold',...
                    'BackgroundColor', [1 1 1]);
                
                set(hList, 'String',...
                    {'BUILD: 1304b',...
                    '-Histogramm PDFs are now exported as linearly scaled values (natural log previously)',...
                    '-Fixed a bug with use of backslash in case of Mac/Linux',...
                    '-Fixed a bug where trajectories where displayed displaced when using a ROI',...
                    '-Project file format reset from v7.3 to v.7 to reduce space consumption',...
                    '-Polynomial and local calibration deactivated',...
                    '-Fixed a bug with initialization of trajectories in a composite',...
                    'BUILD: 1304a',...
                    '-SLIMfast main window is now correctly resized',...
                    '-Fixed bug when generating figure of single trajectory',...
                    '-Particle displacement fit now supports truncation',...
                    'BUILD: 1303e',...
                    '-Single colored trajectories are now generated as single line objects',...
                    '-Line Profile can now be calculated in parallel or orthogonal',...
                    '-Localization window is now quadratic for simplicity',...
                    'BUILD: 1303d',...
                    '-Cluster (DBSCAN) objects can now be combined into one list "Data->Cluster->Pool"',...
                    '-Trajectory objects can now be combined into one list "Data->Trajectory->Pool"',...
                    '-Fixed a bug when combining two objects via "Project->Combine"',...
                    'BUILD: 1303c',...
                    '-Fixed a bug when setting Max.Gap Closure to zero',...
                    'BUILD: 1303b',...
                    '-Fixed bug when copying trajectory data into composite',...
                    'BUILD: 1303a',...
                    '-Fixed an issue with generation of localization data from cluster/trajectory data',...
                    'BUILD: 1302c',...
                    '-Fixed bug when importing old SLIMfast data',...
                    '-Support for loading of multiple Projects at once',...
                    '-Fixed latency when copying or filtering trajectory/cluster objects',...
                    'BUILD: 1302b',...
                    '-Save button for profiles implemented',...
                    '-Fixed bug with particle count when points were moved beyond roi due to calibration',...
                    '-Batch functionality implemented for Localization and Tracking',...
                    '-Immobile Filter implemented',...
                    'BUILD: 1302a',...
                    '-Fixed hierarchy bug when cloning manager objects',...
                    '-Fixed error with profile popup-menu',...
                    '-Fixed frame index when using multi-core localization',...
                    'BUILD: 1301a',...
                    '-Fixed reconstruction when loading modified class object',...
                    '-Fixed a bug when deleting trajectory data',...
                    '-Data information table implemented',...
                    '-Non-linear line profile manager implemented',...
                    '-Distribution manager now shows subset probability',...
                    'only when population fit data is available',...
                    '-Advanced settings profile selection implemented',...
                    '-Fixed a bug in ROI''s µm-width/height display',...
                    'BUILD: 1212a',...
                    '-Tracking option search expansion factor fixed to 3',...
                    '-Localization using multiple cores fixed',...
                    'BUILD: 1211c',...
                    '-Image/Movie export now captures zoomed figure',...
                    '-Jump Series Manager fixed',...
                    '-Co-Localization fixed',...
                    '-ASCII data export now with additional file prefix',...
                    '-Background noise estimation fixed (clipped at zero)',...
                    '-MSDs'' slope changed from 2Dnt to 4Dnt',...
                    'BUILD: 1211b',...
                    '-Roi Manager fixed',...
                    '-Import function fixed',...
                    'BUILD: 1211a',...
                    '-Combination of multiple projects implemented',...
                    '-Button added to de/activate experimental notes',...
                    '-Project Explorer no longer allows selection of data type or channel folder',...
                    'BUILD: 1210a',...
                    '-Signal size distribution/filter implemented',...
                    '-Filehistory implemented',...
                    '-Fixed a bug with manager-autoclosure for loaded data',...
                    '-Co-Localization filter re-implemented',...
                    '-Selection of trajectory line style',...
                    '-Trajectory split tool implemented',...
                    '-Changelog re-implemented',...
                    '-Progressbar allows process interruption for localization, tracking and movie export',...
                    ''})
            end %if
        end
        
        %% query
    end %methods
end %classdef