classdef ManagerClusterSettings < SuperclassManager
    %written by
    %C.P.Richter
    %Division of Biophysics / Group J.Piehler
    %University of Osnabrueck
    
    properties (Hidden,Dependent)
        SigSpat
        TempWeight
        SigTemp
        CritScore
        UseProbScore
        Alpha
        UseLocAlpha
        BoxSpat
        BoxTemp
        
        SearchRad
        ObsProb
        MinT
        MaxT
        NumT
        UniqueCorrespondance
    end %properties
    properties (Hidden,Transient)
        hFig = nan;
        hGraphFig
        
        hProfilePopup
        hProfileSaveButton
        hAxCluster
        hTimsScaleSlider
        hWinPosSlider
        hWinWidthSlider
        hToolbar
        hEvalButton
        
        hAxSpat
        hAxTemp
        hSigTempEdit
        hCritScoreEdit
        hAlphaEdit
        hLocAlphaCheck
        hBoxSpatEdit
        hBoxTempEdit
        
        objKdTree
        objKdTreeTest
        
        NumPnts
        PntList
        
        ClusterID
        PntType
        PntScore
        NumCluster
        
        hPatch
        Vertices
        Faces
    end %properties
    
    methods
        %constructor
        function this = ManagerClusterSettings(parent)
            if nargin == 0
                parent = [];
            end %if
            this = this@SuperclassManager(parent);
            
            if nargin > 0
                check_settings(this)
            end %if
        end %fun
        function check_settings(this)
            this.SrcContainer.SearchRad = ...
                max(1,this.SearchRad);
            this.SrcContainer.ObsProb = ...
                min(100,max(0,this.ObsProb));
            this.SrcContainer.NumT = ...
                max(1,round(this.NumT));
            this.SrcContainer.MaxT = ...
                max(1,min(sum(this.Parent.objImageFile.NumImageFrames)/...
                this.Parent.objImageFile.objChannelConfig.NumAlternatingChannels,...
                round(this.MaxT)));
            this.SrcContainer.MinT = ...
                max(1,min(this.MaxT,round(this.MinT)));
        end %fun
        
        function set_parameter(this,onlyParam)
            %check if gui already open
            if ishandle(this.hFig)
                waitfor(msgbox('CLUSTER MANAGER already open','INFO','help','modal'))
                figure(this.hFig)
                return
            end %if
            if nargin == 1
                onlyParam = 0;
            end %if
            
            y0 = 180;
            
            scrSize = get(0, 'ScreenSize');
            
            this.hFig = figure(...
                'Units','pixels',...
                'Position', [0.5*(scrSize(3)-225) 0.5*(scrSize(4)-y0) 225 y0],...
                'Color', this.FamilyColor,...
                'Name', 'CLUSTER MANAGER',...
                'NumberTitle', 'off',...
                'MenuBar', 'none',...
                'ToolBar', 'none',...
                'IntegerHandle','off',...
                'CloseRequestFcn',@(src,evnt)close_object(this));
            
            y = y0 -20;
            
            uicontrol(...
                'Parent', this.hFig,...
                'Style', 'Text',...
                'Units','pixels',...
                'Position', [5 y 50 15],...
                'FontSize', 8,...
                'String', 'Profile:',...
                'BackgroundColor', this.FamilyColor,...
                'HorizontalAlignment', 'left');
            
            get_actual_profiles(this.SrcContainer)
            this.hProfilePopup = ...
                uicontrol(...
                'Parent', this.hFig,...
                'Style', 'popupmenu',...
                'Units','pixels',...
                'Position', [60 y+1 115 15],...
                'FontSize', 7,...
                'String', this.SrcContainer.Profiles,...
                'Value', find(strcmp(this.SrcContainer.Profile,this.SrcContainer.Profiles)),...
                'BackgroundColor', [1 1 1],...
                'Callback', @(src,evnt)set_Profile(this,src));
            this.hProfileSaveButton = ...
                uicontrol(...
                'Style', 'pushbutton',...
                'Units','pixels',...
                'Position', [180 y 40 15],...
                'FontSize', 8,...
                'String', 'Save',...
                'BackgroundColor', this.FamilyColor,...
                'HorizontalAlignment', 'left',...
                'Callback', @(src,evnt)save_actual_properties_as_profile(this.SrcContainer));
            
            y = y -20;
            
            uicontrol(...
                'Parent', this.hFig,...
                'Style', 'Text',...
                'Units','pixels',...
                'Position', [5 y 170 15],...
                'FontSize', 8,...
                'FontUnits', 'normalized',...
                'String', 'Search Radius [nm]:',...
                'BackgroundColor', this.FamilyColor,...
                'HorizontalAlignment', 'left');
            
            uicontrol(...
                'Parent', this.hFig,...
                'Style', 'edit',...
                'Units','pixels',...
                'Position', [180 y 40 15],...
                'FontSize', 8,...
                'FontUnits', 'normalized',...
                'String', this.SearchRad,...
                'BackgroundColor', [1 1 1],...
                'Callback', @(src,evnt)set_SearchRad(this,src));
            
            %             uicontrol(...
            %                 'Parent', this.hFig,...
            %                 'Style', 'Text',...
            %                 'Units','pixels',...
            %                 'Position', [5 y 170 15],...
            %                 'FontSize', 8,...
            %                 'FontUnits', 'normalized',...
            %                 'String', 'Sigma Spatial Weight[nm]:',...
            %                 'BackgroundColor', this.FamilyColor,...
            %                 'HorizontalAlignment', 'left');
            
            %             uicontrol(...
            %                 'Parent', this.hFig,...
            %                 'Style', 'edit',...
            %                 'Units','pixels',...
            %                 'Position', [180 y 40 15],...
            %                 'FontSize', 8,...
            %                 'FontUnits', 'normalized',...
            %                 'String', this.SigSpat,...
            %                 'BackgroundColor', [1 1 1],...
            %                 'Callback', @(src,evnt)set_SigSpat(this,src));
            
            %             y = y - 160;
            %
            %             this.hAxSpat = ...
            %                 axes(...
            %                 'Parent', this.hFig,...
            %                 'Units','pixels',...
            %                 'OuterPosition', [15 y 215 150],...
            %                 'FontSize', 8,...
            %                 'FontUnits', 'normalized',...
            %                 'XAxisLocation', 'top',...
            %                 'Box', 'off',...
            %                 'YTick', [0.01 0.25 0.75],...
            %                 'YTickLabel', '',...
            %                 'XTick', [0.25 0.55 1],...
            %                 'XTickLabel',round([0.25 0.55 1]./0.33.*this.SigSpat),...
            %                 'NextPlot', 'add') ;
            %             ylabel('Point Weight',...
            %                 'FontUnits', 'normalized');
            %             xlabel('Distance [nm]',...
            %                 'FontUnits', 'normalized',...
            %                 'FontWeight','bold');
            
            %             this.hAxTemp = ...
            %                 axes(...
            %                 'Parent', this.hFig,...
            %                 'Units','pixels',...
            %                 'Position', get(this.hAxSpat,'Position'),...
            %                 'FontSize', 8,...
            %                 'FontUnits', 'normalized',...
            %                 'XAxisLocation', 'bottom',...
            %                 'LineWidth', 1.5,...
            %                 'Box', 'on',...
            %                 'YTick', [0.01 0.25 0.75],...
            %                 'YTickLabel', [0.01 0.25 0.75],...
            %                 'YGrid','on',...
            %                 'XTick', [0.25 0.55 1],...
            %                 'XTickLabel',round([0.25 0.55 1]./0.33.*this.SigTemp),...
            %                 'XGrid','on',...
            %                 'NextPlot', 'add') ;
            %             ylabel('Point Weight',...
            %                 'FontUnits', 'normalized',...
            %                 'FontWeight','bold');
            %             xlabel('Distance [ms]',...
            %                 'FontUnits', 'normalized',...
            %                 'FontWeight','bold');
            %
            %             line(0:0.01:1,exp(-0.5*(0:0.01:1).^2/0.33^2),...
            %                 'Color', [0 0 0], 'Linewidth', 2,...
            %                 'Parent', this.hAxTemp)
            %
            %             y = y - 20;
            %
            %             uicontrol(...
            %                 'Parent', this.hFig,...
            %                 'Style', 'checkbox',...
            %                 'Units','pixels',...
            %                 'Position', [5 y 170 15],...
            %                 'FontSize', 8,...
            %                 'BackgroundColor', this.FamilyColor,...
            %                 'String', 'Include Temporal Information',...
            %                 'Value', this.TempWeight,...
            %                 'Callback', @(src,evnt)set_TempWeight(this,src));
            
            y = y - 20;
            
            uicontrol(...
                'Parent', this.hFig,...
                'Style', 'Text',...
                'Units','pixels',...
                'Position', [5 y 170 15],...
                'FontSize', 8,...
                'FontUnits', 'normalized',...
                'String', 'Observation Probability [%]',...
                'BackgroundColor', this.FamilyColor,...
                'HorizontalAlignment', 'left');
            
            uicontrol(...
                'Parent', this.hFig,...
                'Style', 'edit',...
                'Units','pixels',...
                'Position', [180 y 40 15],...
                'FontSize', 8,...
                'FontUnits', 'normalized',...
                'String', this.ObsProb,...
                'BackgroundColor', [1 1 1],...
                'Callback', @(src,evnt)set_ObsProb(this,src));
            
            %             uicontrol(...
            %                 'Parent', this.hFig,...
            %                 'Style', 'Text',...
            %                 'Units','pixels',...
            %                 'Position', [5 y 170 15],...
            %                 'FontSize', 8,...
            %                 'FontUnits', 'normalized',...
            %                 'String', 'Sigma Temporal Weight [ms]:',...
            %                 'BackgroundColor', this.FamilyColor,...
            %                 'HorizontalAlignment', 'left');
            %
            %             this.hSigTempEdit = ...
            %                 uicontrol(...
            %                 'Parent', this.hFig,...
            %                 'Style', 'edit',...
            %                 'Units','pixels',...
            %                 'Position', [180 y 40 15],...
            %                 'FontSize', 8,...
            %                 'FontUnits', 'normalized',...
            %                 'String', this.SigTemp,...
            %                 'BackgroundColor', [1 1 1],...
            %                 'Callback', @(src,evnt)set_SigTemp(this,src));
            %             if this.TempWeight
            %                 set(this.hSigTempEdit,'Enable', 'on')
            %             else
            %                 set(this.hSigTempEdit,'Enable', 'off')
            %             end %if
            
            %             y = y - 20;
            %
            %             uicontrol(...
            %                 'Parent', this.hFig,...
            %                 'Style', 'Text',...
            %                 'Units','pixels',...
            %                 'Position', [5 y 170 15],...
            %                 'FontSize', 8,...
            %                 'String', 'Critical Point Score:',...
            %                 'BackgroundColor', this.FamilyColor,...
            %                 'HorizontalAlignment', 'left');
            %
            %             this.hCritScoreEdit = ...
            %                 uicontrol(...
            %                 'Parent', this.hFig,...
            %                 'Style', 'edit',...
            %                 'Units','pixels',...
            %                 'Position', [180 y 40 15],...
            %                 'FontSize', 8,...
            %                 'String', this.CritScore,...
            %                 'BackgroundColor', [1 1 1],...
            %                 'Callback', @(src,evnt)set_CritScore(this,src));
            %
            %             y = y - 20;
            %
            %             uicontrol(...
            %                 'Parent', this.hFig,...
            %                 'Style', 'checkbox',...
            %                 'Units','pixels',...
            %                 'Position', [5 y 215 15],...
            %                 'FontSize', 8,...
            %                 'BackgroundColor', this.FamilyColor,...
            %                 'String', 'Estimate Critical Point Score',...
            %                 'Value', this.UseProbScore,...
            %                 'Callback', @(src,evnt)set_UseProbScore(this,src),...
            %                 'Enable','off');
            %
            %             y = y - 20;
            %
            %             uicontrol(...
            %                 'Parent', this.hFig,...
            %                 'Style', 'Text',...
            %                 'Units','pixels',...
            %                 'Position', [5 y 170 15],...
            %                 'FontSize', 8,...
            %                 'String', 'Significance Level:',...
            %                 'BackgroundColor', this.FamilyColor,...
            %                 'HorizontalAlignment', 'left');
            %
            %             this.hAlphaEdit = ...
            %                 uicontrol(...
            %                 'Parent', this.hFig,...
            %                 'Style', 'edit',...
            %                 'Units','pixels',...
            %                 'Position', [180 y 40 15],...
            %                 'FontSize', 8,...
            %                 'String', this.Alpha,...
            %                 'BackgroundColor', [1 1 1],...
            %                 'Callback', @(src,evnt)set_Alpha(this,src));
            
            y = y - 20;
            
            uicontrol(...
                'Parent', this.hFig,...
                'Style', 'Text',...
                'Units','pixels',...
                'Position', [5 y 170 15],...
                'FontSize', 8,...
                'FontUnits', 'normalized',...
                'String', 'Iterations:',...
                'BackgroundColor', this.FamilyColor,...
                'HorizontalAlignment', 'left');
            
            uicontrol(...
                'Parent', this.hFig,...
                'Style', 'edit',...
                'Units','pixels',...
                'Position', [180 y 40 15],...
                'FontSize', 8,...
                'FontUnits', 'normalized',...
                'String', this.NumT,...
                'BackgroundColor', [1 1 1],...
                'Callback', @(src,evnt)set_NumT(this,src));
            
            y = y - 20;
            
            uicontrol(...
                'Parent', this.hFig,...
                'Style', 'Text',...
                'Units','pixels',...
                'Position', [5 y 170 15],...
                'FontSize', 8,...
                'FontUnits', 'normalized',...
                'String', 'Initial Time Window [frame]:',...
                'BackgroundColor', this.FamilyColor,...
                'HorizontalAlignment', 'left');
            
            uicontrol(...
                'Parent', this.hFig,...
                'Style', 'edit',...
                'Units','pixels',...
                'Position', [180 y 40 15],...
                'FontSize', 8,...
                'FontUnits', 'normalized',...
                'String', this.MaxT,...
                'BackgroundColor', [1 1 1],...
                'Callback', @(src,evnt)set_MaxT(this,src));
            
            y = y - 20;
            
            uicontrol(...
                'Parent', this.hFig,...
                'Style', 'Text',...
                'Units','pixels',...
                'Position', [5 y 170 15],...
                'FontSize', 8,...
                'FontUnits', 'normalized',...
                'String', 'Minimal Time Window [frame]:',...
                'BackgroundColor', this.FamilyColor,...
                'HorizontalAlignment', 'left');
            
            uicontrol(...
                'Parent', this.hFig,...
                'Style', 'edit',...
                'Units','pixels',...
                'Position', [180 y 40 15],...
                'FontSize', 8,...
                'FontUnits', 'normalized',...
                'String', this.MinT,...
                'BackgroundColor', [1 1 1],...
                'Callback', @(src,evnt)set_MinT(this,src));
            
            %             this.hLocAlphaCheck = ...
            %                 uicontrol(...
            %                 'Parent', this.hFig,...
            %                 'Style', 'checkbox',...
            %                 'Units','pixels',...
            %                 'Position', [5 y 135 15],...
            %                 'FontSize', 8,...
            %                 'BackgroundColor', this.FamilyColor,...
            %                 'String', 'Local Estimate:',...
            %                 'Value', this.UseLocAlpha,...
            %                 'Callback', @(src,evnt)set_UseLocAlpha(this,src));
            %
            %             this.hBoxSpatEdit = ...
            %                 uicontrol(...
            %                 'Parent', this.hFig,...
            %                 'Style', 'edit',...
            %                 'Units','pixels',...
            %                 'Position', [140 y 40 15],...
            %                 'FontSize', 8,...
            %                 'String', this.BoxSpat,...
            %                 'BackgroundColor', [1 1 1],...
            %                 'Callback', @(src,evnt)set_BoxSpat(this,src));
            %
            %             this.hBoxTempEdit = ...
            %                 uicontrol(...
            %                 'Parent', this.hFig,...
            %                 'Style', 'edit',...
            %                 'Units','pixels',...
            %                 'Position', [180 y 40 15],...
            %                 'FontSize', 8,...
            %                 'String', this.BoxTemp,...
            %                 'BackgroundColor', [1 1 1],...
            %                 'Callback', @(src,evnt)set_BoxTemp(this,src));
            
            %             if this.UseProbScore
            %                 set(this.hCritScoreEdit,'Enable', 'off')
            %                 set([this.hAlphaEdit,...
            %                     this.hLocAlphaCheck],'Enable', 'on')
            %                 if this.UseLocAlpha
            %                     set([this.hBoxSpatEdit,...
            %                         this.hBoxTempEdit],'Enable', 'on')
            %                 else
            %                     set([this.hBoxSpatEdit,...
            %                         this.hBoxTempEdit],'Enable', 'off')
            %                 end %if
            %             else
            %                 set(this.hCritScoreEdit,'Enable', 'on')
            %                 set([this.hAlphaEdit,...
            %                     this.hLocAlphaCheck,...
            %                     this.hBoxSpatEdit,...
            %                     this.hBoxTempEdit],'Enable', 'off')
            %             end %if
            
            y = y -20;
            
                uicontrol(...
                'Style', 'checkbox',...
                'Units','pixels',...
                'Position', [5 y 170 15],...
                'FontSize', 8,...
                'BackgroundColor', this.FamilyColor,...
                'String', 'Unique Correspondance',...
                'Value', this.UniqueCorrespondance,...
                'Callback', @(src,evnt)set_UniqueCorrespondance(this,src));
            
            y = y - 35;
            
            this.hEvalButton = ...
                uicontrol(...
                'Parent', this.hFig,...
                'Style', 'pushbutton',...
                'Units','pixels',...
                'Position', [25 y 75 25],...
                'FontSize', 8,...
                'String', 'Evaluate',...
                'BackgroundColor', this.FamilyColor,...
                'HorizontalAlignment', 'left',...
                'Callback', @(src,evnt)evaluate_dbscan_clustering(this));
            
            uicontrol(...
                'Parent', this.hFig,...
                'Style', 'pushbutton',...
                'Units','pixels',...
                'Position', [125 y 75 25],...
                'FontSize', 8,...
                'String', 'Accept',...
                'BackgroundColor', this.FamilyColor,...
                'HorizontalAlignment', 'left',...
                'Callback', @(src,evnt)construct_density_based_cluster(this.Parent));
            
            hList = get(this.hFig,'Children');
            set(hList,...
                'Units', 'normalized',...
                'FontUnits', 'normalized',...
                'FontWeight','bold')
            set(this.hFig,'Units','pixels',...
                'Position', set_figure_position(225/y0, 0.45/225*y0,'center'))
            set(this.hAxTemp,...
                'Position', get(this.hAxSpat,'Position'));
            
            if ~onlyParam
                initialize_graphs(this)
                initialize_data(this)
            end
        end %fun
        function initialize_graphs(this)
            this.hGraphFig = figure(...
                'Units','pixels',...
                'Position', set_figure_position(1, 0.6, 'center'),...
                'Color', this.FamilyColor,...
                'Name', 'CLUSTER MANAGER',...
                'NumberTitle', 'off',...
                'MenuBar', 'none',...
                'ToolBar', 'none',...
                'IntegerHandle','off',...
                'Renderer','opengl',...
                'CloseRequestFcn',@(src,evnt)close_object(this));
            construct_image_toolbar(this)
            
            this.hAxCluster = ...
                axes(...
                'Parent', this.hGraphFig,...
                'Units','normalized',...
                'OuterPosition', [0.05 0.1 0.95 0.9],...
                'Box', 'on',...
                'XLim', [this.Parent.FieldOfView(1) ...
                this.Parent.FieldOfView(3)].*this.Parent.Px2nm,...
                'XTick',[this.Parent.FieldOfView(1) ...
                mean([this.Parent.FieldOfView(1),this.Parent.FieldOfView(3)]) ...
                this.Parent.FieldOfView(3)].*this.Parent.Px2nm,...
                'XTickLabel', char(num2str((this.Parent.FieldOfView(1)-0.5)),...
                'x [px]', num2str((this.Parent.FieldOfView(3)-0.5))),...
                'YLim', [this.Parent.FieldOfView(2) ...
                this.Parent.FieldOfView(4)].*this.Parent.Px2nm,...
                'YTick',[this.Parent.FieldOfView(2) ...
                mean([this.Parent.FieldOfView(2),this.Parent.FieldOfView(4)]) ...
                this.Parent.FieldOfView(4)].*this.Parent.Px2nm,...
                'YTickLabel', char(num2str((this.Parent.FieldOfView(2)-0.5)),...
                'y [px]', num2str((this.Parent.FieldOfView(4)-0.5))),...
                'YDir','reverse',...
                'ZLim', [this.Parent.LocStart ...
                this.Parent.LocEnd].*this.Parent.Frame2msec,...
                'ZTick',[this.Parent.LocStart ...
                mean([this.Parent.LocStart,this.Parent.LocEnd]) ...
                this.Parent.LocEnd].*this.Parent.Frame2msec,...
                'ZTickLabel', char(num2str(this.Parent.LocStart),...
                'time [frame]', num2str(this.Parent.LocEnd)),...
                'ZGrid','on',...
                'FontSize', 12,...
                'NextPlot', 'add') ;
            
            this.hTimsScaleSlider = ...
                uicontrol(...
                'Parent', this.hGraphFig,...
                'Style', 'slider',...
                'Units', 'normalized',...
                'Position', [0 0.1 0.05 0.9],...
                'Min', -3,...
                'Max', 7,...
                'Value', 0,....
                'SliderStep', [0.01 0.1]);
            addlistener(this.hTimsScaleSlider, 'ContinuousValueChange',...
                @(src,evnt)adjust_time_scale(this));
            
            this.hWinPosSlider = ...
                uicontrol(...
                'Parent', this.hGraphFig,...
                'Style', 'slider',...
                'Units', 'normalized',...
                'Position', [0 0 1 0.05],...
                'Min', this.Parent.FieldOfView(2)*this.Parent.Px2nm,...
                'Max', this.Parent.FieldOfView(4)*this.Parent.Px2nm,...
                'Value', (this.Parent.FieldOfView(2)+this.Parent.FieldOfView(6)/2)*this.Parent.Px2nm,....
                'SliderStep', [0.01 0.1]);
            addlistener(this.hWinPosSlider, 'ContinuousValueChange',...
                @(src,evnt)adjust_displayed_region(this));
            
            this.hWinWidthSlider = ...
                uicontrol(...
                'Parent', this.hGraphFig,...
                'Style', 'slider',...
                'Units', 'normalized',...
                'Position', [0 0.05 1 0.05],...
                'Min', 0,...
                'Max', this.Parent.FieldOfView(6)*this.Parent.Px2nm,...
                'Value', this.Parent.FieldOfView(6)*this.Parent.Px2nm,....
                'SliderStep', [0.01 0.1]);
            addlistener(this.hWinWidthSlider, 'ContinuousValueChange',...
                @(src,evnt)adjust_displayed_region(this));
            
            set(this.hAxCluster, ...
                'CameraTargetMode','manual',...
                'CameraPositionMode','manual',...
                'FontUnits','points')
            
            view(this.hAxCluster,[-63,34])
        end %fun
        function construct_image_toolbar(this)
            this.hToolbar = uitoolbar(...
                'Parent',this.hGraphFig);
            icon = getappdata(0,'icon');
            hSaveKdTree = ...
                uipushtool(...
                'Parent', this.hToolbar,...
                'CData', icon.('Save_kdTree'),...
                'ClickedCallback', @(src,evnt)save_kdTree(this),...
                'Enable','off');
            uitoggletool(...
                'Parent',this.hToolbar,...
                'CData', icon.('Zoom'),...
                'Tag','Zoom',...
                'ClickedCallback', @(src,evnt)set_zoom(src,'hFig',this.hGraphFig))
            uitoggletool(...
                'Parent',this.hToolbar,...
                'CData', icon.('Pan'),...
                'Tag','Pan',...
                'ClickedCallback', @(src,evnt)set_pan(src,'hFig',this.hGraphFig))
            uitoggletool(...
                'Parent',this.hToolbar,...
                'CData', icon.('Rotate'),...
                'Tag','Rotate',...
                'ClickedCallback', @(src,evnt)set_rotate(src,'hAx',this.hAxCluster))
            uipushtool(...
                'Parent', this.hToolbar,...
                'CData', icon.('Point_Score_Distribution'),...
                'Separator','on',...
                'ClickedCallback', @(src,evnt)ClassHistogram(this.Parent,'Point Score Distribution',this))
        end %fun
        
        %% getter
        function sigspat = get.SigSpat(this)
            sigspat = this.SrcContainer.SigSpat;
        end %fun
        function tempweight = get.TempWeight(this)
            tempweight = this.SrcContainer.TempWeight;
        end %fun
        function sigtemp = get.SigTemp(this)
            sigtemp = this.SrcContainer.SigTemp;
        end %fun
        function critscore = get.CritScore(this)
            critscore = this.SrcContainer.CritScore;
        end %fun
        function useprobscore = get.UseProbScore(this)
            useprobscore = this.SrcContainer.UseProbScore;
        end %fun
        function alpha = get.Alpha(this)
            alpha = this.SrcContainer.Alpha;
        end %fun
        function uselocalpha = get.UseLocAlpha(this)
            uselocalpha = this.SrcContainer.UseLocAlpha;
        end %fun
        function boxspat = get.BoxSpat(this)
            boxspat = this.SrcContainer.BoxSpat;
        end %fun
        function boxtemp = get.BoxTemp(this)
            boxtemp = this.SrcContainer.BoxTemp;
        end %fun
        
        function searchrad = get.SearchRad(this)
            searchrad = this.SrcContainer.SearchRad;
        end %fun
        function obsprob = get.ObsProb(this)
            obsprob = this.SrcContainer.ObsProb;
        end %fun
        function numt = get.NumT(this)
            numt = this.SrcContainer.NumT;
        end %fun
        function mint = get.MinT(this)
            mint = this.SrcContainer.MinT;
        end %fun
        function maxt = get.MaxT(this)
            maxt = this.SrcContainer.MaxT;
        end %fun
        function uniquecorrespondance = get.UniqueCorrespondance(this)
            uniquecorrespondance = this.SrcContainer.UniqueCorrespondance;
        end %fun
        
        %% setter
        function set_Profile(this,src)
            content = get(src,'String');
            value = get(src,'Value');
            
            profile = content{value};
            update_profile(this,profile)
        end %fun
        
        function set_SigSpat(this,src)
            value = max(...
                str2double(get(src,'String')),1);
            
            numTargets = numel(this.TargetContainer);
            for idx = 1:numTargets
                this.TargetContainer(idx).SigSpat = value;
            end %for
            this.SrcContainer.SigSpat = value;
            set(src,'String', value)
            
            %adjust axis ticks
            labels = get(this.hAxSpat,'XTick');
            set(this.hAxSpat,'XTickLabel',...
                round(labels./0.33.*value))
            
            update_profile(this,'None')
        end %fun
        function set_TempWeight(this,src)
            value = get(src,'Value');
            
            numTargets = numel(this.TargetContainer);
            for idx = 1:numTargets
                this.TargetContainer(idx).TempWeight = value;
            end %for
            this.SrcContainer.TempWeight = value;
            
            if value
                set(this.hSigTempEdit,'Enable', 'on')
            else
                set(this.hSigTempEdit,'Enable', 'off')
            end %if
            
            update_profile(this,'None')
            
            if this.TempWeight
                this.objKdTree = KDTreeSearcher(this.PntList);
            else
                this.objKdTree = KDTreeSearcher(this.PntList(:,1:2));
            end %if
        end %fun
        function set_SigTemp(this,src)
            %when active minimum equals to 1dt
            value = max(...
                str2double(get(src,'String')),...
                this.Parent.Frame2msec);
            
            numTargets = numel(this.TargetContainer);
            for idx = 1:numTargets
                this.TargetContainer(idx).SigTemp = value;
            end %for
            this.SrcContainer.SigTemp = value;
            set(src,'String', value)
            
            %adjust axis ticks
            labels = get(this.hAxTemp,'XTick');
            set(this.hAxTemp,'XTickLabel',...
                round(labels./0.33.*value))
            
            update_profile(this,'None')
        end %fun
        function set_CritScore(this,src)
            value = max(0,str2double(get(src,'String')));
            
            numTargets = numel(this.TargetContainer);
            for idx = 1:numTargets
                this.TargetContainer(idx).CritScore = value;
            end %for
            this.SrcContainer.CritScore = value;
            
            update_profile(this,'None')
        end %fun
        function set_UseProbScore(this,src)
            this.SrcContainer.UseProbScore = get(src,'Value');
            if this.SrcContainer.UseProbScore
                set(this.hCritScoreEdit,'Enable', 'off')
                set([this.hAlphaEdit,...
                    this.hLocAlphaCheck],'Enable', 'on')
                if this.SrcContainer.UseLocAlpha
                    set([this.hBoxSpatEdit,...
                        this.hBoxTempEdit],'Enable', 'on')
                else
                    set([this.hBoxSpatEdit,...
                        this.hBoxTempEdit],'Enable', 'off')
                end %if
            else
                set(this.hCritScoreEdit,'Enable', 'on')
                set([this.hAlphaEdit,...
                    this.hLocAlphaCheck,...
                    this.hBoxSpatEdit,...
                    this.hBoxTempEdit],'Enable', 'off')
            end %if
            
            update_profile(this,'None')
        end %fun
        function set_Alpha(this,src)
            %significance level between 0 -> 1
            this.SrcContainer.Alpha = min(max(...
                str2double(get(src,'String')),0),1);
            set(src,'String', this.SrcContainer.Alpha)
            
            update_profile(this,'None')
        end %fun
        function set_UseLocAlpha(this,src)
            this.SrcContainer.UseLocAlpha = get(src,'Value');
            if this.SrcContainer.UseLocAlpha
                set([this.hBoxSpatEdit,...
                    this.hBoxTempEdit],'Enable', 'on')
            else
                set([this.hBoxSpatEdit,...
                    this.hBoxTempEdit],'Enable', 'off')
            end %if
            
            update_profile(this,'None')
        end %fun
        function set_BoxSpat(this,src)
            this.SrcContainer.BoxSpat = ...
                str2double(get(src,'String'));
            
            update_profile(this,'None')
        end %fun
        function set_BoxTemp(this,src)
            this.SrcContainer.BoxTemp = ...
                str2double(get(src,'String'));
            
            update_profile(this,'None')
        end %fun
        
        function set_SearchRad(this,src)
            value = max(...
                str2double(get(src,'String')),1);
            
            numTargets = numel(this.TargetContainer);
            for idx = 1:numTargets
                this.TargetContainer(idx).SearchRad = value;
            end %for
            this.SrcContainer.SearchRad = value;
            set(src,'String', value)
            
            update_profile(this,'None')
        end %fun
        function set_ObsProb(this,src)
            value = min(100,max(0,str2double(get(src,'String'))));
            
            numTargets = numel(this.TargetContainer);
            for idx = 1:numTargets
                this.TargetContainer(idx).ObsProb = value;
            end %for
            this.SrcContainer.ObsProb = value;
            
            update_profile(this,'None')
        end %fun
        function set_NumT(this,src)
            value = max(1,round(str2double(get(src,'String'))));
            
            numTargets = numel(this.TargetContainer);
            for idx = 1:numTargets
                this.TargetContainer(idx).NumT = value;
            end %for
            this.SrcContainer.NumT = value;
            set(src,'String', value)
            
            update_profile(this,'None')
        end %fun
        function set_MinT(this,src)
            value = max(1,min(this.MaxT,round(str2double(get(src,'String')))));
            
            numTargets = numel(this.TargetContainer);
            for idx = 1:numTargets
                this.TargetContainer(idx).MinT = value;
            end %for
            this.SrcContainer.MinT = value;
            set(src,'String', value)
            
            update_profile(this,'None')
        end %fun
        function set_MaxT(this,src)
            value = max(this.MinT,min(sum(this.Parent.objImageFile.NumImageFrames)/...
                this.Parent.objImageFile.objChannelConfig.NumAlternatingChannels,...
                round(str2double(get(src,'String')))));
            
            numTargets = numel(this.TargetContainer);
            for idx = 1:numTargets
                this.TargetContainer(idx).MaxT = value;
            end %for
            this.SrcContainer.MaxT = value;
            set(src,'String', value)
            
            update_profile(this,'None')
        end %fun
        function set_UniqueCorrespondance(this,src)
                        value = get(src,'Value');

                        numTargets = numel(this.TargetContainer);
            for idx = 1:numTargets
                this.TargetContainer(idx).UniqueCorrespondance = value;
            end %for
            this.SrcContainer.UniqueCorrespondance = value;
            
            update_profile(this,'None')
        end %fun
        
        %%
        function update_profile(this,profile)
            this.SrcContainer.Profile = profile;
            switch profile
                case 'None'
                    set(this.hProfilePopup,'Value',...
                        find(strcmp('None',this.SrcContainer.Profiles)))
                case 'Standard'
                    set_standard_properties(this.SrcContainer)
                    check_settings(this)
                    
                    close_object(this)
                    set_parameter(this)
                otherwise
                    SLIMfastPath = getappdata(0,'SLIMfastPath');
                    filename = fullfile(SLIMfastPath, ...
                        'Profiles', [this.SrcContainer.Profile '.txt']);
                    load_settings_from_disc(this.SrcContainer,filename)
                    check_settings(this)
                    
                    close_object(this)
                    set_parameter(this)
            end %switch
        end %fun
        
        function adjust_time_scale(this)
            set(this.hAxCluster,'DataAspectRatio',...
                [1 1 exp(get(this.hTimsScaleSlider,'Value'))])
        end %fun
        function adjust_displayed_region(this)
            %             if ~isempty(this.hPatch)
            %                 patchPos = get(this.hPatch,'YData');
            
            winPos = get(this.hWinPosSlider,'Value');
            winWidth = max(1e-3,get(this.hWinWidthSlider,'Value'));
            
            %                 good = double(patchPos(1,:) > winPos-winWidth/2 &...
            %                     patchPos(1,:) < winPos+winWidth/2);
            %                 set(this.hPatch,...
            %                     'FaceVertexAlphaData',good')
            set(this.hAxCluster,'YLim',[winPos-winWidth/2 winPos+winWidth/2])
            %             end %if
        end %fun
        
        function initialize_data(this)
            if isempty(this.PntList)
                this.PntList = [[this.Parent.Data.Position_X ...
                    this.Parent.Data.Position_Y]*this.Parent.Px2nm ...
                    this.Parent.Data.Time*this.Parent.Frame2msec];
                this.NumPnts = this.Parent.NumParticles;
                
                %                 hMsg = msgbox('Please wait while generating Kd-Tree','','warn');
                %                 set(hMsg,'CloseRequestFcn','','DeleteFcn','')
                %                 hList = get(hMsg,'Children');
                %                 delete(hList(3))
                
                %initialize tree
                %                 if this.TempWeight
                %                     this.objKdTree = KDTreeSearcher(this.PntList);
                %                 else
                %                     this.objKdTree = KDTreeSearcher(this.PntList(:,1:2));
                %                 end %if
                %                 delete(hMsg)
            else
                if ~isempty(this.ClusterID) && ...
                        ishandle(this.hAxCluster) %(=clustering done)
                    initialize_particle_polygons(this)
                end %if
            end %if
        end %fun
        function evaluate_dbscan_clustering(this)
            %evaluate cluster
            dbscan(this);
            
            %draw cluster representation
            if isempty(this.hPatch)
                initialize_particle_polygons(this)
            else
                update_particle_polygons(this)
            end %if
        end %fun
        
        %         function dbscan(this)
        %             %DBSCAN (Density-Based Spatial Clustering of Applications with Noise)
        %             %is a data clustering algorithm proposed by Martin Ester, Hans-Peter Kriegel,
        %             %Jörg Sander and Xiaowei Xu in 1996.
        %
        %             %written by
        %             %C.P.Richter
        %             %Division of Biophysics / Group J.Piehler
        %             %University of Osnabrueck
        %
        %             this.ClusterID = nan(this.NumPnts,1); %unclassified
        %             this.PntScore = nan(this.NumPnts,1);
        %             this.PntType = zeros(this.NumPnts,1);
        %
        %             sigSpat = this.SigSpat;
        %             if this.TempWeight
        %                 sigTemp = this.SigTemp;
        %             end %if
        %
        %             %initialize
        %             progressbar('Evaluate Points...')
        %
        %             clusterIdx = 1;
        %             for pntIdx = 1:this.NumPnts
        %                 seed = this.PntList(pntIdx,:);
        %                 if isnan(this.ClusterID(pntIdx))
        %                     output = expand_cluster;
        %                     if output
        %                         %initialize new cluster
        %                         clusterIdx = clusterIdx+1;
        %                     end %if
        %                 end %if
        %
        %                 %update
        %                 progressbar(pntIdx/this.NumPnts)
        %             end %for
        %
        %             %classify as border points
        %             this.PntType(this.PntType == -1 & this.ClusterID ~= 0) = 0;
        %
        %             this.NumCluster = sum(unique(this.ClusterID)>0); %(= #, noise cluster excluded)
        %
        %             function output = expand_cluster
        %                 [neighborIdx score] = find_neighbors(seed);
        %                 this.PntScore(pntIdx) = score;
        %
        %                 if score < this.CritScore
        %                     output = false;
        %                     %point is put into noise cluster
        %                     this.ClusterID(pntIdx) = 0;
        %                     %point is classified as noise
        %                     this.PntType(pntIdx) = -1;
        %
        %                     % !point can still be a border point
        %                     return
        %                 else
        %                     output = true;
        %                     %point is put into respective cluster
        %                     this.ClusterID(pntIdx) = clusterIdx;
        %                     %point is classified as core point
        %                     this.PntType(pntIdx) = 1;
        %
        %                     %remove ref point from set
        %                     neighborIdx(neighborIdx == pntIdx) = [];
        %                     %add to list for cluster propagation
        %                     seeds = [this.PntList(neighborIdx,:) neighborIdx];
        %                     while ~isempty(seeds)
        %                         %iterate until all points for cluster propagation
        %                         %are exhausted
        %                         [neighborIdx score] = find_neighbors(seeds(1,1:end-1));
        %                         this.PntScore(seeds(1,end)) = score;
        %                         if score >= this.CritScore
        %                             %point is put into respective cluster
        %                             this.ClusterID(seeds(1,end)) = clusterIdx;
        %                             %point is classified as core point
        %                             this.PntType(seeds(1,end)) = 1; %core point
        %
        %                             neighborIdx(neighborIdx == seeds(1,end)) = [];
        %                             result = [this.PntList(neighborIdx,:) neighborIdx];
        %
        %                             %check if points are already assigned to a cluster
        %                             good = (isnan(this.ClusterID(neighborIdx)) |...
        %                                 this.ClusterID(neighborIdx) == 0) &...
        %                                 ~ismember(neighborIdx,seeds(:,end));
        %                             %if not (=nan) add to actual cluster
        %                             this.ClusterID(neighborIdx(good)) = clusterIdx;
        %                             %add to list for cluster propagation
        %                             seeds = [seeds; result(good,:)];
        %                         end %if
        %                         %remove point processed
        %                         seeds(1,:) = [];
        %                     end %while
        %                 end %if
        %                 function [neighborIdx score] = find_neighbors(refPnt)
        %                     %kd tree search
        %                     if this.TempWeight
        %                         neighborIdx = cell2mat(rangesearch(this.objKdTree, ...
        %                             refPnt(1:3),max(sigSpat,sigTemp)*3))';
        %
        %                         score = nansum(exp(-(...
        %                             (this.PntList(neighborIdx,1)-refPnt(1)).^2/2/sigSpat.^2+...
        %                             (this.PntList(neighborIdx,2)-refPnt(2)).^2/2/sigSpat.^2+...
        %                             (this.PntList(neighborIdx,3)-refPnt(3)).^2/2/sigTemp.^2)));
        %                     else
        %                         neighborIdx = cell2mat(rangesearch(this.objKdTree, ...
        %                             refPnt(1:2),sigSpat*3))';
        %
        %                         score = nansum(exp(-(...
        %                             (this.PntList(neighborIdx,1)-refPnt(1)).^2/2/sigSpat.^2+...
        %                             (this.PntList(neighborIdx,2)-refPnt(2)).^2/2/sigSpat.^2)));
        %                     end %if
        %                     %correct for reference point in the set
        %                     score = score - 1;
        %                 end %nested1
        %             end %nested0
        %         end %fun
        
        function dbscan(this)
            %             switch this.ScaleT
            %                 case {'log10','lg'}
            T = unique(round(logspace(log10(this.MinT),log10(this.MaxT),this.NumT))); %[frames] temporal search windows used in the iterative filtering process
            %                 case {'linear','lin'}
            %                     T = unique(round(linspace(this.MinT,this.MaxT,this.NumT)));
            %             end %switch
            
            corrFactor = this.ObsProb/100;
            
            SML.j = this.PntList(:,1);
            SML.i = this.PntList(:,2);
            SML.t = round(this.PntList(:,3)/this.Parent.Frame2msec);
            
            %% CLUSTERING
            progressbar('Evaluate Points...')
            
            %% iterative segmentation of the clusters
            take = 1:this.NumPnts; %we start with all points in the game
            clusterID = ones(this.NumPnts,1); %initialize as noise
            pntType = -1*ones(this.NumPnts,1); %initialize as noise
            
            %starting from the long lasting clusters as these will be picked up with higher fidelity
            %(at smaller T, the chance for false identification is increased due to the less stringent requirements)
            for idxT = numel(T):-1:1
                numCluster = max(clusterID) - 1; % ID = 1 being the noise cluster
                
                %search for pot. links (observations that potentially stem from the same emitter)
                pntNN = DBSCAN_pot_link([SML.i(take) SML.j(take)],this.SearchRad);
                
                critScore = corrFactor*T(idxT);
                %apply forward and backward clustering with DBSCAN
                [clusterID(take),pntType(take)] = ...
                    DBSCAN_fwd_rev_cluster(...
                    get_cross_field_value(SML,take),...
                    pntNN,T(idxT),...
                    critScore,...
                    'OnlyNN',this.UniqueCorrespondance,...
                    'idOffset',numCluster);
                
                %% start next iteration on the set of unclassified points
                take = find(pntType == -1);
                
                %update
                progressbar(1-(idxT-1)/numel(T))
            end %for
            
            this.NumCluster = max(clusterID) - 1;
            this.ClusterID = clusterID - 1;
            pntType(pntType==0) = -1;
            this.PntType = pntType;
        end %fun
        
        function initialize_particle_polygons(this)
            %             if isempty(this.Faces) && isempty(this.Vertices)
            %                 radius = ones(this.NumPnts,1)*100;
            %
            %                 x = [1 0; 1 1; 1 0; 1 -1; 1 0; 1 0]*...
            %                     [this.PntList(:,1),radius]';
            %                 y = [1 0; 1 0; 1 1; 1 0; 1 -1; 1 0]*...
            %                     [this.PntList(:,2),radius]';
            %                 z = [1 1; 1 0; 1 0; 1 0; 1 0; 1 -1]*...
            %                     [this.PntList(:,3),radius]';
            %                 this.Vertices = [x(:) y(:) z(:)]+100;
            %
            %                 %construct bi-pyramidial structure
            %                 faceIdx = repmat([1 2 3; 1 3 4; 1 4 5; 1 5 2;...
            %                     6 2 3; 6 3 4; 6 4 5; 6 5 2],this.NumPnts,1);
            %                 face = reshape(repmat(0:6:6*(this.NumPnts-1),24,1),[3 this.NumPnts*8]);
            %                 this.Faces = faceIdx+face';
            %             end %if
            %
            %             color = [[1 1 1]; lines(this.NumCluster)];
            %             cIdx = reshape(repmat((this.ClusterID+1)',8,1),[1 8*this.NumPnts]);
            %
            %             this.hPatch = patch(...
            %                 'AlphaDataMapping','none',...
            %                 'Faces',this.Faces(cIdx>1,:),...
            %                 'Vertices',this.Vertices,...
            %                 'FaceVertexCData', color(cIdx(cIdx>1),:),...
            %                 'FaceAlpha','flat',...
            %                 'EdgeAlpha','flat',...
            %                 'FaceVertexAlphaData', ones(sum(cIdx>1),1),...
            %                 'FaceColor', 'flat',...
            %                 'Parent',this.hAxCluster);
            %             set(this.hAxCluster,'DataAspectRatio', [1 1 1]);
            %             axis(this.hAxCluster, ...
            %                 [this.Parent.FieldOfView([1 3 2 4])*this.Parent.Px2nm ...
            %                 [this.Parent.LocStart this.Parent.LocEnd]*...
            %                 this.Parent.Frame2msec], 'vis3d')
            cla(this.hAxCluster)
            
            SML.j = this.PntList(:,1);
            SML.i = this.PntList(:,2);
            SML.t = round(this.PntList(:,3));
            
            %noise
            take = (this.PntType == -1) | (this.PntType == 0);
            line('xdata',SML.j(take),'ydata',SML.i(take),'zdata',SML.t(take),'marker','.','color','k','linestyle','none','Parent',this.hAxCluster)
            
            for idxCluster = reshape(unique(this.ClusterID),1,[])
                if idxCluster == 0
                    %skip noise cluster
                    continue
                end
                %     if clusterSize(idxCluster) > 10
                clusterColor = rand(1,3);
                
                take = (this.ClusterID == idxCluster) & (this.PntType == 1);
                line('xdata',SML.j(take),'ydata',SML.i(take),'zdata',SML.t(take),'marker','.','color',clusterColor,'markersize',15,'linestyle','none','Parent',this.hAxCluster)
                
                %%mark caps
                idxMinCap = min(SML.t(take));
                line('xdata',mean(SML.j(take)),'ydata',mean(SML.i(take)),'zdata',idxMinCap,'marker','square','color',clusterColor,'markersize',20,'linewidth',2,'linestyle','none','Parent',this.hAxCluster)
                idxMaxCap = max(SML.t(take));
                line('xdata',mean(SML.j(take)),'ydata',mean(SML.i(take)),'zdata',idxMaxCap,'marker','square','color',clusterColor,'markersize',20,'linewidth',2,'linestyle','none','Parent',this.hAxCluster)
                
                %%mark border points
                take = (this.ClusterID == idxCluster) & (this.PntType == -1);
                line('xdata',SML.j(take),'ydata',SML.i(take),'zdata',SML.t(take),'marker','o','markersize',6,'color',clusterColor,'linestyle','none','Parent',this.hAxCluster)
                %     end
            end %for
            
        end %fun
        function update_particle_polygons(this)
            initialize_particle_polygons(this)
            %             color = [[1 1 1]; rand(this.NumCluster,3)];
            %             cIdx = reshape(repmat((this.ClusterID+1)',8,1),...
            %                 [1 8*this.NumPnts]);
            %             set(this.hPatch,...
            %                 'Faces',this.Faces(cIdx>1,:),...
            %                 'FaceVertexCData', color(cIdx(cIdx>1),:));
            %             adjust_displayed_region(this)
        end %fun
        
        %%
        function saveObj = saveobj(this)
            saveObj = saveobj@SuperclassManager(this);
        end %fun
        function close_object(this)
            if ishandle(this.hFig)
                delete(this.hFig)
            end %if
            if ishandle(this.hGraphFig)
                delete(this.hGraphFig)
            end %if
        end %fun
        function delete_object(this)
            if ishandle(this.hFig)
                delete(this.hFig)
            end %if
            if ishandle(this.hGraphFig)
                delete(this.hGraphFig)
            end %if
            
            delete_object@SuperclassManager(this)
        end %fun
    end %methods
    
    methods (Access = protected)
        function cpObj = copyElement(this)
            cpObj = copyElement@SuperclassManager(this);
            
            cpObj.hFig = nan;
            cpObj.PntList = [];
            cpObj.Faces = [];
            cpObj.Vertices = [];
        end %fun
    end %methods
    methods (Static)
        function this = loadobj(S)
            this = ManagerClusterSettings;
            this = loadobj@SuperclassManager(this,S);
        end %fun
    end %methods
end %classdef